[[redirects]]
from = "/login"
to = "/"
status = 200
force = true

[[redirects]]
from = "/quick-math"
to = "/"
status = 200
force = true

[[redirects]]
from = "/leaderboard/quick-math"
to = "/"
status = 200
force = true
